services:
  - type: web
    name: connect4
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
